### ISSUE TITLE
\v matches the line break in Python

### ISSUE THREAD

**Issue by Serious54088** [firasdib/Regex101#1676]
## Bug Description

Testing Python regex on regex101， \v can match the line break character.  It seems to me this is an incorrect result.

In some flavors, like Perl or PCRE, \v is a shorthand that matches any vertical whitespace character. 
But in Python, \v matches only the vertical tab (ASCII 0x0B), can not match the line break character.

```python
>>> re.sub(r'\v', '+', 'a\nb\nc')
'a\nb\nc'
# \v no match
```

### Reproduction steps

REGEX:
```
\v
```
TEST STRING:
```
a
b
c
```
SUBSTITUTION:
```
+
```
RESULT TEXT:
```
a+b+c
```

### Expected Outcome

```
a
b
c
```

**Comment by firasdib** [comment]
Thank you, I will have this resolved in the next major release.

**Comment by CarlitoGil** [comment]
Hi @firasdib 

This is still happening. Could you check it, please?

**Comment by Serious54088** [comment]
This is an automatic reply, confirming that your email was received. I will reply as soon as possible. Thank you!
