### ISSUE TITLE
NaNth subpattern

### ISSUE THREAD

**Issue by rentalhost** [firasdib/Regex101#261]
Go to community codes and see `MATCHING EMAIL ADDRESSES PER RFC5322`. Pass cursor over the any recursion. I'll show something like:

> **Recursion**: Reference to `NaNth` subpattern.

![image](https://cloud.githubusercontent.com/assets/421851/6802346/6768c7b0-d20e-11e4-8a22-9ad498119f70.png)

If do you open this code it'll work properly:

> **Recursion**: Subpattern reference to group named `local_part`.

![image](https://cloud.githubusercontent.com/assets/421851/6802361/8e8e031e-d20e-11e4-9152-d7cfbd14137d.png)

**Comment by firasdib** [comment]
Thanks for the report! I have already fixed this in my local instance but have not yet pushed the changes live, since it's a major update. Rest assured, it will all be fine soon enough :)!

**Comment by rentalhost** [comment]
Thanks!

**Comment by TWiStErRob** [comment]
@firasdib Found the same thing, still not released or regeressed?
![image](https://cloud.githubusercontent.com/assets/2906988/18814635/02552b98-831a-11e6-81a0-79b9346030bd.png)

**Comment by firasdib** [comment]
@TWiStErRob That is the old version still, the new version has not been released yet (i'm working on getting it out asap)
