### ISSUE TITLE
In Chrome unable to open Substitution section

### ISSUE THREAD

**Issue by MNF** [firasdib/Regex101#473]
In Chrome when trying to open Substitution section- clicking "+" , it's very often doesn't work. It changes + to '-', but doesn't show Substitution section. It seems that if the test string is big- feels the whole page, the failure of  Substitution expansion is more likely. As a workaround I've found that  opening Dev.tools (F12) force substitution section to appear. Also if open the site in the different tab- it also works.
I've checked Edge and IE- they work as expected.

**Comment by nhahtdh** [comment]
This looks like a duplicate of https://github.com/firasdib/Regex101/issues/456

**Comment by Kiyos** [comment]
I'm using Chrome 50.0.2661.94 m (64-bit) on Windows 7 and I can confirm the existence of this bug. No JavaScript or Network errors can be found in the Developer Tools. The (+) button starts working properly right after any viewport resize event (i.e. opening Developer Tools in docked mode, or even resizing the browser window).

**Comment by miparnisari** [comment]
+1, using Chrome

**Comment by firasdib** [comment]
Thanks for the report. I've fixed this in the new version of the site which I hope to release soon.

**Comment by waldi** [comment]
the substitution section still does not open correctly on chrome for me..
Chrome version 52.0.2743.116 (64-bit) 
Mac OS X

Following works: 
I press on (+) and resize the window -> section opens
I press (-) -> it hides
I resize window and then press on (+) -> section opens

**Comment by nhahtdh** [comment]
@waldi As stated above, the fix is in the new version, which is not yet release.

**Comment by firasdib** [comment]
I have asked @OnlineCop to look into a fix for the existing website in the mean time.
