### ISSUE TITLE
Misleading warning for optional regex

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#685]
This warning feels out of place for `(x)?`:

> A repeated capturing group will only capture the last iteration. Put a capturing group around the repeated group to capture all iterations or use a non-capturing group instead if you're not interested in the data

As far as I know `((?:x)?)` would yield the exact same results.

![image](https://cloud.githubusercontent.com/assets/2906988/19212018/72e70c4e-8d49-11e6-9ab4-b66b190c4b84.png)

**Comment by firasdib** [comment]
fixed

**Comment by 12345ieee** [comment]
This error is still present when using a named capture group, e.g. `(?P<name>word)?`.
I indeed do not see it when using `(word)?`, but the two should be functionally equivalent.

**Comment by firasdib** [comment]
A logical fallacy in the code, this has now been adjusted. Thanks for pointing it out.
